# Generated by Django 3.1.3 on 2020-11-20 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_authors', models.CharField(default='', max_length=100)),
                ('book_title', models.CharField(default='', max_length=100)),
                ('book_overview', models.TextField(default='')),
                ('book_genres', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.AutoField(primary_key=True, serialize=False)),
                ('movie_genres', models.TextField(default='')),
                ('movie_popularity', models.FloatField()),
                ('movie_title', models.CharField(default='', max_length=50)),
                ('movie_vote_average', models.FloatField()),
            ],
        ),
    ]
