# Generated by Django 3.1.3 on 2020-11-20 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_book_rating_movie_rating_song_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_overview',
            field=models.TextField(default=''),
        ),
    ]
