# Generated by Django 3.1.3 on 2020-11-20 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201120_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='movie_popularity',
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_cover_url',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_title',
            field=models.CharField(default='', max_length=256),
        ),
    ]
